gitea:
  admin:
    username: gitea_admin
    password: "ChangeMe123!"
    email: admin@example.com
  config:
    database:
      DB_TYPE: sqlite3
    log:
      LEVEL: warn
persistence:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
