gitea:
  admin:
    username: gitea_admin
    password: "ChangeMe123!"
    email: admin@example.com
  config:
    database:
      DB_TYPE: sqlite3
    log:
      LEVEL: debug
persistence:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
