apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitea-multi-env
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: staging
          - env: prod
          - env: qa
  template:
    metadata:
      name: 'gitea-{{env}}'
    spec:
      project: default
      sources:
        - repoURL: https://dl.gitea.com/charts/
          chart: gitea
          targetRevision: "10.4.1"
          helm:
            valueFiles:
              - $values/values/values-{{env}}.yaml
        - repoURL: https://github.com/Andrii30/k8s-gitops-multi-env.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: 'gitea-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
